### PR TITLE
Add more input formats.

### PR DESCRIPTION
**Pull request by Tilps**
Type 4 is same as type 3, but rule 50 plane will be divided by 100 by lc0 code on input to the net.
This will obsolete the hack in the training code that divides by 99 and then multiplies the weights by 99. I chose 100 here because I would also like to scale the moves left head output by 100 or so - and 99 is a number that only has meaning in the context of the very specific details of rule 50 plane.
Type 5 is the same as type 4, but the side to move plane will be provided (probably as aux +3 or aux + 6, haven't decided yet) - this is useful for armageddon or other non-color symmetrical variants.
I considered adding a hectoplies variant on type 1, but I don't think we really need it as type 3 seems to be pretty good.

### CODE REVIEW

**Comment by borg323** [comment]
Is it worth considering something like what @mooskagh suggested in <https://github.com/LeelaChessZero/lczero-common/pull/9#issuecomment-552930963> and make InputFormat repeated instead of optional? It will be a bit awkward, but probably cleaner in the long run.

**Comment by Tilps** [comment]
I don't see how that could work with our current training data format. Its not all a set of flags, so there would have to be some mixing format to populate the current input_format integer in the training data.

**Comment by borg323** [comment]
I was thinking the new values would need to be first so that old code that is not looping will get an unknown value. But maybe I misunderstand how repeated fields work.

**Comment by mooskagh** [comment]
Repeated fields indeed work that way, but the problem is that the training data is not a protobuf but a fixed-sized struct, so it's not easy to have repeated fields there.
I'm all for having proper training data format (not necessary a protobuf, can be something fast and custom), but there are some obstacles as far as I remember.

**Comment by Tilps** [comment]
Any chance of this getting approved? I'd like to implement these for 0.26.

**Comment by borg323** [comment]
What about slecting the values as if it is a bitfield? Something like:
```
    INPUT_112_WITH_CANONICALIZATION_HECTOPLIES = 7;
    INPUT_112_WITH_CANONICALIZATION_HECTOPLIES_ARMAGEDDON = 15;
```
Hopefully this will make transitioning to a repeated field easier.

**Comment by Tilps** [comment]
I'd argue that hectoplies doesn't need to be a flag - its just what we should always have done, and all future formats should have it on.
I think I'd leave a larger gap to enumerate more 'basic advances', but I could make armageddon 132 instead of 5 - that sounds like a safe enough space for the base input format evolution.

**Comment by borg323** [comment]
Seems fine to me. @mooskagh?

**Pull request merged**
